### ISSUE TITLE
Edit favicon & translations

### ISSUE THREAD

**Issue by NoltoxGit** [SNDST00M/material-dynmap#122]
## 🧱 Bug Report

• I'm using the latest version of `material-dynmap` available.

Hey, I installed MaterialDynmap but when reloading (f5) my dynmap; the icon I had defined before was changed by something else ... Would it be possible to change the favicon?

And also would it be possible to translate some messages?

- Server version: 1.16.5 
- Dynmap version: 3.3-beta-3-591
- Browser version: Firefox 95.0.2 
- Extensions: /
- OS version: Windows 11

**Comment by SNDST00M** [comment]
I don't believe I hardcode any English in the extension. You may need to rename your world titles in the actual Dynmap configuration, try ask for help in https://discord.com/invite/rS8qjhk if you don't know how.

I think the best way to support custom favicon is to only override the default Dynmap icon, I'll look into it after my laptop comes back from the shop.

**Comment by SNDST00M** [comment]
I'll create a new issue for the favicon, cos I figured out a solution
