### ISSUE TITLE
Worlds & Perspectives not visible

### ISSUE THREAD

**Issue by HCookie** [SNDST00M/material-dynmap#50]
## 🧱 Bug Report

- [x] I'm using the latest version of `material-dynmap` available.
- [x] I searched [existing issues][material-dynmap-issues], open & closed. Yes, my issue is new.

#### Describe the bug

After adding material design to Dynmap, all options to select perspectives and worlds were removed. They are visible without material-dynmap.
It defaults to the main flat world

I am running dynmap Fabric Edition, on a Fabric Instance
#### Screenshots

![Issue](https://user-images.githubusercontent.com/48088699/129468605-b37fb68a-ecec-42da-a8b5-0fe15a7dd7fb.png)

#### Expected behavior

To be able to change between worlds and perspectives

#### Additional context

- Browser version: Viewed on Firefox and Chrome
- Extensions: MC: Fabric

[material-dynmap-issues]: https://github.com/SNDST00M/material-dynmap/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by SNDST00M** [comment]
You'll need to link your server please

**Comment by HCookie** [comment]
Sent you an email

**Comment by SNDST00M** [comment]
Confirmed in v5.0.0, the following line throws an error when the clock component is disabled:

https://github.com/SNDST00M/material-dynmap/blob/v0.5.0/src/app.js#L43

Will release a fix ASAP alongside the other v0.5.1 fixes. Stretch goal to publish today 💪🏾

**Comment by HCookie** [comment]
I see that you have fixed the issue, 
Is there a way to use that branch, or do I need to wait for the commit to main and update to the cdn?

**Comment by SNDST00M** [comment]
I'll push it in the next hour.

**Comment by SNDST00M** [comment]
I have pushed the fix, it'll be live on the sitewide link in the next few hours
